version: "3.9"
services:
  api:
    image: ghcr.io/zinebmouman/music-api:latest
    container_name: music-api
    ports:
      - "8000:8000"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    container_name: music-ui
    environment:
      - API_URL=http://api:8000   # UI parle au service "api" via le r√©seau compose
    ports:
      - "8501:8501"
    depends_on:
      - api
